services:
  mysql:
    image: mysql:8.0
    container_name: mysql-enrique
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: apiexamen
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - exam-enrique

  app:
    build: .
    container_name: spring-enrique
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/apiexamen
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: enriqueEx4men2025miSuperClaveSegura!#
    networks:
      - exam-enrique

volumes:
  mysql-data:

networks:
  exam-enrique:
